/*
 * Demo integrations marketplace. Frontend-only — no OAuth, no network.
 * Read scope is always presented before write scope; write scope is
 * described as approval-gated and inactive in demo mode.
 */

import { DEMO_META, type Integration } from "./types";

export const DEMO_INTEGRATIONS: readonly Integration[] = [
  // CRM
  {
    ...DEMO_META,
    id: "INT-followupboss",
    name: "Follow Up Boss",
    category: "crm",
    status: "connected_read_only",
    readScope: ["contacts", "deals", "activity"],
    writeScope: ["create_note (approval required)"],
    health: "Healthy (demo)",
    setupSteps: ["Authorize read access", "Map pipeline stages", "Confirm sync"],
    lastSync: "2026-05-29T17:00:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-lofty",
    name: "Lofty",
    category: "crm",
    status: "not_connected",
    readScope: ["contacts", "smart_lists"],
    writeScope: ["update_stage (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read access", "Select smart lists", "Confirm sync"],
    lastSync: null,
  },
  {
    ...DEMO_META,
    id: "INT-kvcore",
    name: "kvCORE",
    category: "crm",
    status: "not_connected",
    readScope: ["leads", "campaigns"],
    writeScope: ["assign_lead (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read access", "Map lead routing", "Confirm sync"],
    lastSync: null,
  },
  {
    ...DEMO_META,
    id: "INT-hubspot",
    name: "HubSpot",
    category: "crm",
    status: "not_connected",
    readScope: ["contacts", "deals"],
    writeScope: ["create_task (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read access", "Map deal stages", "Confirm sync"],
    lastSync: null,
  },
  {
    ...DEMO_META,
    id: "INT-salesforce",
    name: "Salesforce",
    category: "crm",
    status: "not_connected",
    readScope: ["leads", "opportunities"],
    writeScope: ["update_opportunity (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read access", "Map objects", "Confirm sync"],
    lastSync: null,
  },
  // Lead sources
  {
    ...DEMO_META,
    id: "INT-zillow",
    name: "Zillow",
    category: "lead_source",
    status: "connected_read_only",
    readScope: ["inbound_leads"],
    writeScope: [],
    health: "Healthy (demo)",
    setupSteps: ["Connect lead feed", "Confirm routing"],
    lastSync: "2026-05-29T16:45:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-realtor",
    name: "Realtor.com",
    category: "lead_source",
    status: "degraded",
    readScope: ["inbound_leads"],
    writeScope: [],
    health: "Degraded — delayed feed (demo)",
    setupSteps: ["Connect lead feed", "Confirm routing"],
    lastSync: "2026-05-29T11:10:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-facebook-lead-ads",
    name: "Facebook Lead Ads",
    category: "lead_source",
    status: "connected_read_only",
    readScope: ["lead_forms"],
    writeScope: [],
    health: "Healthy (demo)",
    setupSteps: ["Connect page", "Select lead forms"],
    lastSync: "2026-05-29T15:30:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-website-forms",
    name: "Website Forms",
    category: "lead_source",
    status: "connected_read_only",
    readScope: ["form_submissions"],
    writeScope: [],
    health: "Healthy (demo)",
    setupSteps: ["Add embed snippet", "Confirm test submission"],
    lastSync: "2026-05-29T16:20:00Z",
  },
  // Calendar / booking
  {
    ...DEMO_META,
    id: "INT-google-calendar",
    name: "Google Calendar",
    category: "calendar",
    status: "write_approval_required",
    readScope: ["events", "availability"],
    writeScope: ["create_event (approval required)"],
    health: "Healthy (demo)",
    setupSteps: ["Authorize read", "Request write approval"],
    lastSync: "2026-05-29T17:05:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-calcom",
    name: "Cal.com",
    category: "calendar",
    status: "connected_read_only",
    readScope: ["bookings", "availability"],
    writeScope: ["create_booking (approval required)"],
    health: "Healthy (demo)",
    setupSteps: ["Connect Cal.com", "Map event types"],
    lastSync: "2026-05-29T16:55:00Z",
  },
  // Communication
  {
    ...DEMO_META,
    id: "INT-gmail",
    name: "Gmail",
    category: "communication",
    status: "not_connected",
    readScope: ["thread_metadata"],
    writeScope: ["send_email (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read", "Request send approval"],
    lastSync: null,
  },
  {
    ...DEMO_META,
    id: "INT-slack",
    name: "Slack",
    category: "communication",
    status: "connected_read_only",
    readScope: ["channel_messages"],
    writeScope: ["post_message (approval required)"],
    health: "Healthy (demo)",
    setupSteps: ["Install app", "Select channels"],
    lastSync: "2026-05-29T16:40:00Z",
  },
  {
    ...DEMO_META,
    id: "INT-twilio",
    name: "Twilio",
    category: "communication",
    status: "not_connected",
    readScope: ["call_logs"],
    writeScope: ["send_sms (approval required)"],
    health: "Not connected",
    setupSteps: ["Connect number", "Request send approval"],
    lastSync: null,
  },
  // Workspace
  {
    ...DEMO_META,
    id: "INT-google-sheets",
    name: "Google Sheets",
    category: "workspace",
    status: "not_connected",
    readScope: ["sheet_values"],
    writeScope: ["append_row (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read", "Pick a spreadsheet"],
    lastSync: null,
  },
  {
    ...DEMO_META,
    id: "INT-notion",
    name: "Notion",
    category: "workspace",
    status: "not_connected",
    readScope: ["database_pages"],
    writeScope: ["create_page (approval required)"],
    health: "Not connected",
    setupSteps: ["Authorize read", "Select databases"],
    lastSync: null,
  },
];
