"""
WebSocket Handler — real-time audio pipeline per call.
Twilio audio in → Deepgram STT → PAS Engine → ElevenLabs TTS → Twilio audio out

Post-call:
  - Lead memory upserted in Supabase
  - Call summary generated by Claude
  - Slack summary sent to brokerage channel
  - Agent appointment reminder sent via SMS + Slack
"""

import asyncio
import json
import logging
import base64

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from app.engine.state_machine import PASEngine
from app.services.stt.deepgram_client import DeepgramStreamClient
from app.services.tts.elevenlabs_client import synthesize_speech
from app.db.call_logger import update_call_outcome
from app.db.event_logger import log_event_bg
from app.db.lead_memory import get_lead, upsert_lead, mark_booked
from app.db.brokerage_store import get_brokerage_by_id, increment_call_count
from app.db.agent_store import get_best_available_agent, record_assignment
from app.services.training.self_trainer import maybe_train
from app.config import get_settings
from app.services.summary.call_summary import generate_call_summary
from app.services.notifications.slack_client import send_call_summary, send_agent_reminder
from app.services.notifications.sms_client import send_booking_confirmation_sms
from app.services.notifications.lead_alerts import dispatch_lead_notification

# PAS134 — outcomes that trigger a sales-critical lead alert (email + Slack).
_NOTIFY_OUTCOMES = {"callback_requested", "booked"}
from app.utils.call_store import active_calls
from app.utils.slot_formatter import format_slot_for_speech

router = APIRouter()
logger = logging.getLogger("pas.websocket")


@router.websocket("/media-stream/{call_sid}")
async def media_stream(websocket: WebSocket, call_sid: str):
    # SECURITY: only accept media streams whose call_sid was registered by a
    # legitimate /twilio/voice (or /demo/call) webhook. Unknown call_sids are
    # rejected before any STT/TTS resources spin up — closes the cost-DoS
    # path against ElevenLabs/Deepgram from random WebSocket connections.
    if call_sid not in active_calls:
        logger.warning(f"[{call_sid}] WebSocket rejected — unknown call_sid")
        await websocket.close(code=4401, reason="Unknown call_sid")
        return

    await websocket.accept()
    logger.info(f"[{call_sid}] WebSocket connected")

    stream_sid = None
    caller = "unknown"

    # Retrieve brokerage + lead context set by the Twilio webhook
    call_ctx = active_calls.get(call_sid, {})
    brokerage = call_ctx.get("brokerage") or {}
    lead_context = call_ctx.get("lead") or {}

    brokerage_id = brokerage.get("id", "demo")

    # Initialise engine — brokerage config injected for white-labelling
    engine = PASEngine(call_sid=call_sid, lead_context=lead_context or None, brokerage=brokerage)
    dg_client = DeepgramStreamClient()

    audio_queue: asyncio.Queue = asyncio.Queue()
    tts_queue: asyncio.Queue = asyncio.Queue()

    async def handle_transcript(transcript: str, is_final: bool):
        if not is_final or not transcript.strip():
            return
        logger.info(f"[{call_sid}] TRANSCRIPT: {transcript!r}")
        response_text, done = await engine.process_input(transcript)

        # Speak the response before acting on transfer/done flags
        if response_text:
            logger.info(f"[{call_sid}] PAS → TTS: {response_text!r}")
            audio_bytes = await synthesize_speech(response_text)
            await tts_queue.put((audio_bytes, False))  # don't stop stream yet
            await asyncio.sleep(2)  # let TTS finish playing

        # Warm transfer: lead asked to speak to a human
        if engine.pending_transfer:
            engine.pending_transfer = False
            await _warm_transfer(call_sid, engine, brokerage)
            await tts_queue.put((b"", True))  # signal stream end
            return

        if done:
            await tts_queue.put((b"", True))

    async def deepgram_task():
        async with dg_client.connect(on_transcript=handle_transcript) as dg_conn:
            while True:
                chunk = await audio_queue.get()
                if chunk is None:
                    break
                await dg_conn.send(chunk)

    async def tts_sender_task():
        while True:
            item = await tts_queue.get()
            if item is None:
                break
            audio_bytes, call_done = item
            b64_audio = base64.b64encode(audio_bytes).decode("utf-8")
            if stream_sid:
                await websocket.send_text(json.dumps({
                    "event": "media",
                    "streamSid": stream_sid,
                    "media": {"payload": b64_audio}
                }))
            if call_done:
                await asyncio.sleep(3)
                if stream_sid:
                    await websocket.send_text(json.dumps({
                        "event": "stop",
                        "streamSid": stream_sid
                    }))

    dg_task = asyncio.create_task(deepgram_task())
    tts_task = asyncio.create_task(tts_sender_task())

    # Play greeting immediately
    greeting_text = engine.get_greeting()
    greeting_audio = await synthesize_speech(greeting_text)
    await tts_queue.put((greeting_audio, False))

    try:
        async for message in websocket.iter_text():
            data = json.loads(message)
            event = data.get("event")

            if event == "start":
                stream_sid = data["start"]["streamSid"]
                params = data["start"].get("customParameters", {})
                caller = params.get("caller", "unknown")
                engine.state.lead.phone_number = caller

                # Load lead memory for inbound returning callers
                if not lead_context and caller != "unknown":
                    existing = get_lead(brokerage_id, caller)
                    if existing and (existing.get("total_calls") or 0) > 0:
                        engine.state.lead.name = existing.get("name") or ""
                        engine.state.lead.email = existing.get("email") or ""
                        engine.state.lead.intent = existing.get("intent") or ""
                        engine.state.lead.budget = existing.get("budget") or ""
                        engine.state.lead.source = "returning"
                        logger.info(f"[{call_sid}] Returning caller — memory loaded for {caller}")

                logger.info(f"[{call_sid}] Stream started | caller={caller}")

            elif event == "media":
                raw_audio = base64.b64decode(data["media"]["payload"])
                await audio_queue.put(raw_audio)

            elif event == "stop":
                logger.info(f"[{call_sid}] Stream stopped")
                break

    except WebSocketDisconnect:
        logger.info(f"[{call_sid}] WebSocket disconnected")
    except Exception as e:
        logger.error(f"[{call_sid}] WebSocket error: {e}", exc_info=True)
    finally:
        await audio_queue.put(None)
        await tts_queue.put(None)
        await asyncio.gather(dg_task, tts_task, return_exceptions=True)

        outcome = engine.get_outcome()
        transcript = engine.get_full_transcript()
        metadata = engine.get_metadata()
        lead = engine.state.lead
        duration = metadata.get("duration_seconds", 0)

        # Persist call record
        await update_call_outcome(
            call_sid=call_sid,
            outcome=outcome,
            transcript=transcript,
            metadata=metadata,
        )

        log_event_bg(
            "call.ended",
            brokerage_id=brokerage_id,
            call_id=call_sid,
            event_category="call",
            event_source="websocket",
            state=metadata.get("final_state"),
            payload={
                "outcome": outcome,
                "duration_seconds": duration,
                "final_state": metadata.get("final_state"),
                "states_visited": metadata.get("states_visited"),
                "is_outbound": metadata.get("is_outbound"),
                "objections_detected": metadata.get("objections_detected"),
            },
        )

        # Increment call count; trigger self-training if threshold reached
        new_count = increment_call_count(brokerage_id)
        asyncio.create_task(maybe_train(brokerage_id, new_count))

        # Post-call tasks: lead memory, summary, notifications
        asyncio.create_task(_post_call_tasks(
            call_sid=call_sid,
            brokerage=brokerage,
            lead=lead,
            outcome=outcome,
            transcript=transcript,
            duration=duration,
            assigned_agent_id=engine.assigned_agent_id,
        ))

        active_calls.pop(call_sid, None)
        logger.info(f"[{call_sid}] Call closed | outcome={outcome}")


async def _warm_transfer(call_sid: str, engine: "PASEngine", brokerage: dict):
    """
    Redirect the live Twilio call to the best available human agent.
    Uses Twilio REST API to update the call with new TwiML mid-call.
    If no agent is available, PAS offers a callback instead.
    """
    from twilio.rest import Client
    settings = get_settings()
    brokerage_id = brokerage.get("id", "demo")
    lead = engine.state.lead

    agent = get_best_available_agent(
        brokerage_id=brokerage_id,
        intent=lead.intent,
        language="en",
    )

    if agent and agent.get("phone"):
        agent_phone = agent["phone"]
        agent_name = agent["name"]
        engine.assigned_agent_id = agent.get("id")

        # Assign agent immediately so they know a call is coming
        record_assignment(agent["id"])

        twiml = (
            f"<Response>"
            f"<Say>Connecting you now. Please hold.</Say>"
            f"<Dial callerId='{brokerage.get('twilio_phone', settings.TWILIO_PHONE_NUMBER)}'>"
            f"<Number>{agent_phone}</Number>"
            f"</Dial>"
            f"</Response>"
        )
        logger.info(f"[{call_sid}] Warm transfer → {agent_name} ({agent_phone})")
    else:
        # No agent available — offer callback
        twiml = (
            "<Response>"
            "<Say>I'm sorry, all our agents are currently with clients. "
            "Someone will call you back within 15 minutes. Thank you!</Say>"
            "<Hangup/>"
            "</Response>"
        )
        logger.info(f"[{call_sid}] No available agents — offering callback")

    try:
        client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        client.calls(call_sid).update(twiml=twiml)
    except Exception as e:
        logger.error(f"[{call_sid}] Warm transfer failed: {e}")


async def _post_call_tasks(
    call_sid: str,
    brokerage: dict,
    lead,
    outcome: str,
    transcript: str,
    duration: int,
    assigned_agent_id: str = None,
):
    """Runs after the WebSocket closes — non-blocking background work."""
    from app.db.agent_store import get_agent
    brokerage_id = brokerage.get("id", "demo")
    phone = lead.phone_number
    slot_text = format_slot_for_speech(lead.booking_slot) if lead.booking_slot else ""

    # 1. Upsert lead memory
    lead_updates = {
        "name": lead.name,
        "email": lead.email,
        "intent": lead.intent,
        "budget": lead.budget,
        "timeline": lead.timeline,
        "notes": lead.property_interest,
        "last_call_at": __import__("datetime").datetime.now(__import__("datetime").timezone.utc).isoformat(),
    }
    if outcome == "booked":
        lead_updates["last_booked_at"] = lead_updates["last_call_at"]

    upsert_lead(brokerage_id, phone, lead_updates)

    # 2. Generate summary with Claude
    summary = await generate_call_summary(
        transcript=transcript,
        outcome=outcome,
        lead=lead.__dict__,
        duration_seconds=duration,
    )

    # 3. Send Slack summary to brokerage
    slack_webhook = brokerage.get("slack_webhook_url", "")
    if slack_webhook:
        await send_call_summary(
            webhook_url=slack_webhook,
            summary=summary,
            outcome=outcome,
            lead=lead.__dict__,
            duration_seconds=duration,
        )

    # 4. If booked — route to best agent and notify them
    if outcome == "booked" and slot_text:
        # Use the assigned agent (from warm transfer) or find the best available one
        agent = None
        if assigned_agent_id:
            agent = get_agent(assigned_agent_id)

        if not agent:
            from app.db.agent_store import get_best_available_agent
            agent = get_best_available_agent(
                brokerage_id=brokerage_id,
                intent=lead.intent,
            )

        if agent:
            agent_phone = agent.get("phone", "")
            agent_name = agent.get("name", "Agent")
            slack_mention = (
                f"<@{agent['slack_member_id']}>" if agent.get("slack_member_id")
                else f"@{agent_name}"
            )
            # Record appointment against this agent
            from app.db.agent_store import record_assignment
            record_assignment(agent["id"])

            if agent_phone:
                await send_booking_confirmation_sms(agent_phone, agent_name, slot_text)
            if slack_webhook:
                await send_agent_reminder(
                    webhook_url=slack_webhook,
                    agent_name_or_mention=slack_mention,
                    lead=lead.__dict__,
                    slot_readable=slot_text,
                )
        else:
            # No specific agent — fall back to brokerage-level notification
            fallback_phone = brokerage.get("agent_phone", "")
            if fallback_phone:
                await send_booking_confirmation_sms(
                    fallback_phone, brokerage.get("agent_name", "Team"), slot_text
                )

    # PAS134 — sales-critical lead alert (email + Slack). Runs alongside
    # the existing rich Slack call summary above; this one is intentionally
    # short and email-friendly so brokerages get value outside the portal.
    if outcome in _NOTIFY_OUTCOMES:
        try:
            await dispatch_lead_notification(
                call_sid=call_sid,
                brokerage=brokerage,
                outcome=outcome,
                lead=lead.__dict__,
            )
        except Exception as e:
            logger.warning(f"[{call_sid}] Lead notification skipped: {e}")

    logger.info(f"[{call_sid}] Post-call tasks complete | outcome={outcome}")
